### ISSUE TITLE
An unnecessary empty line gets added when a comment is present in a JSON array

### ISSUE THREAD

**Issue by giact** [electrovir/prettier-plugin-multiline-arrays#14]
When a JSON like this is Prettied...

```jsonc
{
  "data": [
    "one",
    // comment
    "two"
  ]
}
```

... it gets formatted into this:

```jsonc
{
  "data": [
    "one",
    // comment
    "two"

  ]
}
```

I added a test for it here:

giact/prettier-plugin-multiline-arrays@07e6eba1f815db65e0d6443dc78fedfcde857675

**Comment by eric-coker** [comment]
Related issue is that if there are no elements in the array but there is a comment, the plugin errors out:
```
{
  "data": [
    // comment
  ]
}
```
Error output: Found "[" but first indent child was not a line.

**Comment by electrovir** [comment]
Thanks both of you for the feedback!
The fix for these are in progress now.
@eric-coker I've already figured out a valid fix for your issue. @giact still working on a fix for your issue.

Unless some other big issue comes up, the next release of this package should have the fix for both of these issues. I will update this issue when that gets out.

**Comment by electrovir** [comment]
Resolved in the now-published version [v1.1.1](https://www.npmjs.com/package/prettier-plugin-multiline-arrays/v/1.1.1). Please re-open this ticket if that does not work for you! (All test are passing though so I think we're good.)

**Comment by eric-coker** [comment]
Awesome. Thanks for the great plugin!

**Comment by giact** [comment]
I have been using it for a few days, and no other issues with comments inside arrays, so far. Thanks for the fix! 👍🏻
